### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by ramdheeraj-uoa** [INFO-523-Exercises/project-final-Byte-Busters#1]
The following is the peer review of the project proposal by [Data Diggers]. The team members that participated in this review are 

- Ram Dheeraj Kamarajugadda - @ramdheeraj-uoa
- Daniel Shevelev - @shahmatyUA
- Kashyap Sai Prasad Nadendla - @KashyapNadendla
- Shreya Kolte - @shreyakolte
- Abhishek Deore - @abhishekdeore

- Describe the goal of the project.

 The project aims to gain a deeper understanding of the microclimatic effects of urbanization by analysing the weather pattern anomalies and temperature distributions.

- Describe the data used or collected.

Climatological and hourly time-series data has been collected from several weather stations run by the National Weather Service (NWS), Federal Aviation Administration (FAA), and Department of Defense (DOD). The significant attributes include Wind Gust Speed , Dry Bulb Temperature, Precipitation Levels, Dew Point Temperature, Pressure - Average Sea Level, Relative Humidity.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

It is quite unclear about the approach as the analysis plan has not been provided, although we could identify that Anomaly detection algorithms will be implemented and classification models for anomalies will be developed from the plan of attack.

- Is there anything that is unclear from the proposal?

The Problem Objective looks complex and could have been simpler to understand for the viewer or could be explained in a better way.

- Provide constructive feedback on how the team might be able to improve their project.

To improve the project , 

1.The question the team is trying to address could be more clear.
2.The team could draft an analysis plan explaining all the necessary steps in the plan.
3.We suggest splitting the research question into two parts instead of one .

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The topic seems interesting and we are curious to know how the team identifies weather pattern anomalies and what are the different classification models the team is going to develop.

- Provide constructive feedback on any issues with file and/or code organization.

We identified no issues with the file/code organization .

- (Optional) Any further comments or feedback?

We are looking forward for the performance analysis , results and the presentation .

**Comment by kendall-beaver** [comment]
Hi Ram Dheeraj et. al., 

Thank you for your review of our proposal. We've taken all of your group's comments into the next draft of our proposal, specifically making our project objective more clear--that is, classifying different levels or heat "intensities" of Urban Heat Islands--and also including an analysis plan, as well as making our questions more clear by splitting them up into two questions with an explanation and approach of how we're going to answer each question. 

Anyways, the feedback from your group has been extremely valuable in helping us improve our proposal, so once again, thank you! :)

-The Byte Busters
