### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by bharath03-a** [INFO-523-Exercises/project-final-Byte-Busters#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Vishal Bhashyaam - @vishalbhashyaam
- Joel Jojo - @joeljojo1310
- Pranshu Singh Rawat - @pranshusinghrawat
- Shashwat Singh - @shashwatsinghds
- Bharath Velamala - @bharath03-a

- Describe the goal of the project.
The primary goal of this project is to detect anomalies in weather patterns by analyzing the Urban Heat Islands dataset. The project will utilize Data Mining and Machine Learning technologies, focusing on distinct demographic areas such as Dallas, Arlington, and Denton.

- Describe the data used or collected.
The dataset, sourced from the National Center for Environmental Information, contains hourly time-series climate data. It includes specific columns pertinent to the problem statement, such as Dry Bulb Temperature and Precipitation Levels.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The approach to the problem statement has not been clearly described. While it can be partially discerned from the weekly plan of attack, explicitly outlining the methodology would enhance organization. The planned tasks indicate that exploratory data analysis, feature engineering for feature selection, and the development of classification models to detect and visualize anomalies will be conducted.

- Is there anything that is unclear from the proposal?
The clarity and organization of the proposal would be improved with a distinct mention of the approach and motivation. Inclusion of an initial data analysis, such as data types and structures, would provide a clearer understanding of the dataset.

- Provide constructive feedback on how the team might be able to improve their project.
The proposal could be more informative with a clear and organized presentation of approach and motivation. A detailed summary of the dataset analysis, including record counts and feature numbers, would be beneficial. Expanding the project scope by adding another problem statement could also fully utilize the dataset.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The identification of weather pattern anomalies across areas with varying population densities and urban development levels is particularly intriguing. The choice of classification models and the accuracy levels achieved will be of interest. The team's motivation for selecting this dataset is also a point of curiosity.

- Provide constructive feedback on any issues with file and/or code organization.
Clarity on the number of data points in the dataset and statistics for the features involved would be valuable.

- (Optional) Any further comments or feedback?
The weekly tasks are well-specified and organized, and the repository organization is clearly outlined.

Looking forward to your final project implementation!

**Comment by kendall-beaver** [comment]
Hi Bharath et. al., 

Thank you for your review of our proposal. We've taken all of your group's comments into the next draft of our proposal, specifically including two questions instead of one and adding an explanation of each question. We've also included our datasets and the specific columns that we'll be using, and we've also gotten more clear about what our overall objective is (classifying different levels or heat "intensities" of Urban Heat Islands) and how we're going to tackle this goal through multi-class classification and trend analysis. 

The feedback from your group has been tremendously valuable in helping us improve our proposal, so once again thank you! :)

Signed,
The (Who-You-Gonna-Call?) Byte Busters
