### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by shashwatsinghds** [INFO-523-Exercises/project-final-Byte-Busters#4]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

- Vishal Bhashyaam - @vishalbhashyaam
- Joel Jojo - @joeljojo1310
- Pranshu Singh Rawat - @pranshusinghrawat
- Shashwat Singh - @shashwatsinghds
- Bharath Velamala - @bharath03-a
- ...
---

#### 1. Purpose of Code
- [ x] Clearly defined and understood
- [x] Ambiguous or unclear

---

#### 2. Code Quality

- [x] Code is clean, readable, and well-organized
- [x] Adequate comments explaining complex or tricky code sections
- [x] Variables, methods, and classes have meaningful names
- [x] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Documentation

- [x] Code documentation (e.g., comments) is sufficient
- [x] Readme or other documentation updated if necessary

---

#### 4. Best Practices

- [x] No hardcoded values; constants used appropriately
- [x] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [x] Code avoids repetition and promotes reusability

---

#### 5. Additional Comments

- Can get rid of warnings present on the ipynb ( For reference- https://stackoverflow.com/questions/15777951/how-to-suppress-pandas-future-warning)
-  Some code is commented and not used. For professional presentation, can get rid of it
- In the preprocessing of data for different cities, we can combine the common steps of EDA and create a function and pass the name of the dataset as a parameter.
- Update readme with appropriate information.
---

#### 6. Recommendation

- [x] Approved - ready to be merged
- [x] Approved with minor issues - can be addressed later
- [x] Requires changes - provide feedback and request another review

---

**Comment by kendall-beaver** [comment]
Note: The first section "Purpose of Code" has a typo in the checkmark field and was actually checked off by the Feature Finders, but we went ahead and corrected this as well as everything else in this issue.

**Comment by kendall-beaver** [comment]
We have updated the README file; gotten rid of commented code that wasn't being used; and most importantly, we've combined the three datasets into one dataset, which not only makes it easier to read but makes it easier to perform additional analytical functions.

Thanks for all of your feedback! It definitely helped us out. :)
