### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by shashwatsinghds** [INFO-523-Exercises/project-final-Byte-Busters#6]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

-Vishal Bhashyaam - @vishalbhashyaam
-Joel Jojo - @joeljojo1310
-Pranshu Singh Rawat - @pranshusinghrawat
-Shashwat Singh - @shashwatsinghds
-Bharath Velamala - @bharath03-a

- Content: Is the research question well designed and is the data being used relevant to the research question?

--The data is well designed and they have touched upon a very interesting topic for their research. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

--They had brilliant visualizations and and had relevant interpretations.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

-- The presentation was clearly showed that they put in a lot of time and effort towards the project and the result was some great insights from the data. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

-- They had excellent organisation with very well thought out slides. They explained the features and the goal of the task correctly.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
-- The team's presentation was good. We believe few people extended their time a little more than they should have and they went for 15 minutes which is 3 times the time that was suggested. However, We don't mean in it in a negative way as the presentation was engaging and full of engaging slides.

**Comment by kendall-beaver** [comment]
Oh wow, Pattern Pioneers! Thank you so much your feedback. Even though we didn't review your group, we all discussed how much we loved the layout and visual aspects of your presentation and the problem you were trying to solve of tackling Amazon shopping experiences, as we're all Amazon shoppers to some degree.

Anyways, thank you once again for your feedback - it means a lot to us!

-The Byte Busters
