### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by abhishekdeore** [INFO-523-Exercises/project-final-Byte-Busters#7]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 
[Abhishek Deore] - @[abhishekdeore]
[Daniel shevelev - @[shahmatyUA]
[Ram Dheeraj Kamarajugadda] - @[ramdheeraj-uoa]
[Shreya Kolte] - @[shreyakolte]
[Kashyap Nadendla] - @[kashyapnadendla]

- Content: Is the research question well designed and is the data being used relevant to the research question?

--The research question in this project was formulated effectively, and the data gathered was notably pertinent to the question being addressed.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

--The team effectively utilized visualizations for their data, with the plots generally being clear and informative. However, there was a challenge in interpreting one particular time series plot initially.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

--The project appears to have been carefully and methodically structured, and based on the quality of their presentation, it is evident that significant time and effort were invested in its execution.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

--Indeed, the presentation slides were effectively structured, featuring a clear layout without excessive text. The inclusion of figures provided a comprehensive visual explanation of the project's workflow.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

--The team delivered an impressive presentation, which clearly exhibited thorough preparation. Their presentation style did not suggest reliance on a script, indicating a strong grasp of the material. Additionally, each member contributed meaningful insights about the project, ensuring a comprehensive understanding of their work.

**Comment by kendall-beaver** [comment]
Oh wow, Data Diggers! Thank you so much for your feedback! Even though we weren't assigned to review your presentation we did discuss your presentation afterwards and actually thought you did a great job analyzing health data and it's correlation to strokes - definitely important and life-saving insights that the medical field needs. Anyways, thanks again for your feedback, it really does mean a lot to us! :)

-The Byte Busters
